export const SpotifyConstants = {
    LOGIN: "LOGIN",
    LOGOUT: "LOGOUT",
    REFRESH_TOKEN: 'REFRESH_TOKEN',
    CHANGE_TRACK_URI: 'CHANGE_TRACK_URI',
    CHANGE_ACCESS_TOKEN: 'CHANGE_ACCESS_TOKEN',
    CHANGE_PLAYING: 'CHANGE_PLAYING',
    CHANGE_CONTEXT_URI: 'CHANGE_CONTEXT_URI',
    REPEAT_TRACK: 'REPEAT_TRACK',
    POSITION_MS: 'POSITION_MS',
    USER: 'USER',
    QUERY: 'QUERY'
  };
  